apiVersion: apps/v1
kind: Deployment
metadata:
  name: chapter-03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
        version: v3
    spec:
      containers:
        - name: flask-app
          image: flask-app:v3
          command: [ "flask", "--app=main", "run" ]
          args: [ "--host={{ .Values.app.config.ip }}", "--port={{ .Values.app.config.port }}" ]
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.container.config.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: app.name
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: app.version
