apiVersion: v1
kind: Service
metadata:
  namespace: app-demo
  name: chapter-01
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32700